#define COL_WHITE "FFFFFF"
#define COL_RED "F81414"
#define COL_LIGHTBLUE "00CED1"
#define COL_TITLE "25AFFE"
#define COL_GREY "C3C3C3" 
#define COL_WHITE "FFFFFF" 
#define COL_RED "F81414" 
#define COL_GREEN "00FF22" 
#define COL_ORANGE "FF9900" 
#define COL_BLACK "000000"

#define COLOR_DOC "0x9966FF"
#define COLOR_LIGHTRED 0xFF6347FF
//#define COLOR_LIGHTRED 0xFF6347AA
#define COLOR_SERVER2 0xA9C4E4FF
#define EMBED_SERVER2 "{A9C4E4}"

#define EMBED_RED "{FF0000}"
#define EMBED_WHITE "{FFFFFF}"
#define EMBED_YELLOW "{00FF00}"
#define EMBED_GREEN "{808040}"
#define EMBED_BLUE "{0000FF}"
#define EMBED_LIGHTBLUE "{8080FF}"
#define EMBED_GRAY "{949494}"
#define EMBED_CYAN "{00FFFF}"

#define TAXI_DUTY 0xFF7F5000
#define LSFD_COLOR 0xFF7D7DFF
#define COLOR_STATS1 0xE2FFFFFF
#define COLOR_STATS2 0xCCE6E6FF
#define FACTION_OOC 0x7BDDA5AA
#define COLOR_HELPS 0xFFEC8B00
#define LSPD_DUTY 0x8c8cfeff
#define LSFD_DUTY 0xfe8281ff
#define DOCS_DUTY 0x9900ff
#define COLOR_POLICECHAT 0x9999FFFF
#define COLOR_LSPD 0x63AFF00A
#define COLOR_DPURPLE 0x000080FF
#define COLOR_PMOUT 0xF6EA51AA
#define COLOR_PMIN 0xF6D600AA
#define COLOR_ADGREEN 0x00E100FF
#define COLOR_RADIO 0xFDE39DAA
#define COLOR_GRAD1 0xFFFFFFFF
#define COLOR_GRAD2 0xBFC0C2FF
#define COLOR_GRAD3 0xCBCCCEFF
#define COLOR_GRAD4 0xD8D8D8FF
#define COLOR_GRAD5 0xE3E3E3FF
#define COLOR_GRAD6 0xF0F0F0FF
#define COLOR_GRAD7 0xB4B5B7FF
#define COLOR_GREY 0xAFAFAFAA
#define COLOR_GREEN 0x33AA3300
#define COLOR_GREENFORADVERT (0x33CC33FF)
#define COLOR_GREEN2 0x36A71700
#define COLOR_HOUSE 0xCCFFDDFF
#define HOUSE_GREEN 0xFFFFFFAA
#define COLOR_SYSTEM 0xEFEFF7AA
#define COLOR_GROVE 0x00FF00FF
#define COLOR_RED 0xAA3333AA
#define TEAM_CYAN 1
#define COLOR_NICEBLUE 0x25affeAA
#define COLOR_LIGHTBLUE 0x33CCFFAA
#define COLOR_LIGHTGREEN 0x9ACD32AA
#define COLOR_WT 0x10ce96AA
#define COLOR_GOLD 	0xF6C861AA
#define COLOR_YELLOW 0xDABB3EAA
#define COLOR_YELLOWMY 0xFFC46AAA
#define COLOR_YELLOW2 0xF5DEB3AA
#define COLOR_YELLOW3 0xFFFF00FF
#define COLOR_BLUE 0x2641FEAA
#define COLOR_WHITE 0xFFFFFFAA
#define COLOR_DRUG 0xC41E3AAA
#define COLOR_FADE1 0xE6E6E6E6
#define COLOR_FADE2 0xC8C8C8C8
#define COLOR_FADE3 0xAAAAAAAA
#define COLOR_FADE4 0x8C8C8C8C
#define COLOR_FADE5 0x6E6E6E6E
#define COLOR_PURPLE 0xC2A2DAAA
#define COLOR_DBLUE 0x2641FEAA
#define COLOR_ALLDEPT 0xFF8282AA
#define COLOR_ALLDEPTOOC 0xe08efeAA
#define COLOR_NEWS 0x458E1DAA
#define COLOR_BLACK 0x000000AA
#define COLOR_YELLOWG 0xFFFF00AA
#define COLOR_ORANGE 0xFF9900AA
#define TEAM_HIT_COLOR 0xFFFFFF00
#define COLOR_OOC 0xB1C8FBAA
#define COLOR_REPORT 0xFFFF91FF
    
    //0x408080FF
#define TEAM_ADMIN_COLOR 0xFF634700
    
#define ADVERT_COLOR 0x00D900C8
#define COLOR_CONNECT 0xC0C0C0FF
#define HELPER_DUTY 0x8b5d2e00
#define COLOR_GREY 0xAFAFAFAA
#define COLOR_MAGENTA 0xFF00FFFF
#define COLOR_FLBLUE 0x6495EDAA
#define COLOR_BROWN 0XA52A2AAA
#define COLOR_CORAL 0xFF7F50AA
#define COLOR_MEDIUMAQUA 0x83BFBFAA
#define COLOR_MEDIUMMAGENTA 0x8B008BAA 
#define COLOR_GREY 0xAFAFAFAA
#define COLOR_ACTIVEBORDER 0xB4B4B4FF
#define COLOR_ACTIVECAPTION 0x99B4D1FF
#define COLOR_ACTIVECAPTIONTEXT 0x000000FF
#define COLOR_ALICEBLUE 0xF0F8FFFF
#define COLOR_ANTIQUEWHITE 0xFAEBD7FF
#define COLOR_APPWORKSPACE 0xABABABFF
#define COLOR_AQUA 0x00FFFFFF
#define COLOR_AQUAMARINE 0x7FFFD4FF
#define COLOR_AZURE 0xF0FFFFFF
#define COLOR_BISQUE 0xFFE4C4FF
#define COLOR_BLANCHEDALMOND 0xFFEBCDFF
#define COLOR_BURLYWOOD 0xDEB887FF
#define COLOR_BUTTONFACE 0xF0F0F0FF
#define COLOR_BUTTONSHADOW 0xA0A0A0FF
#define COLOR_CADETBLUE 0x5F9EA0FF
#define COLOR_CHARTREUSE 0x7FFF00FF
#define COLOR_CONTROL 0xF0F0F0FF
#define COLOR_CONTROLDARK 0xA0A0A0FF
#define COLOR_CONTROLDARKDARK 0x696969FF
#define COLOR_CONTROLLIGHT 0xE3E3E3FF
#define COLOR_CONTROLLIGHTLIGHT 0xFFFFFFFF
#define COLOR_CONTROLTEXT 0x000000FF
#define COLOR_CORNFLOWERBLUE 0x6495EDFF
#define COLOR_CORNSILK 0xFFF8DCFF
#define COLOR_CRIMSON 0xDC143CFF
#define COLOR_CYAN 0x00FFFFFF
#define COLOR_DARKBLUE 0x00008BFF
#define COLOR_DARKGREEN 0x33AA33FF
#define COLOR_DARKCYAN 0x008B8BFF
#define COLOR_DARKGOLDENROD 0xB8860BFF
#define COLOR_DARKGRAY 0xA9A9A9FF
#define COLOR_DARKKHAKI 0xBDB76BFF
#define COLOR_DARKMAGENTA 0x8B008BFF
#define COLOR_DARKOLIVEGREEN 0x556B2FFF
#define COLOR_DARKORCHID 0x9932CCFF
#define COLOR_DARKRED 0x8B0000FF
#define COLOR_DARKSALMON 0xE9967AFF
#define COLOR_DARKSEAGREEN 0x8FBC8BFF
#define COLOR_DARKSLATEBLUE 0x483D8BFF
#define COLOR_DARKSLATEGRAY 0x2F4F4FFF
#define COLOR_DARKTURQUOISE 0x00CED1FF
#define COLOR_DARKVIOLET 0x9400D3FF
#define COLOR_DEEPPINK 0xFF1493FF
#define COLOR_DEEPSKYBLUE 0x00BFFFFF
#define COLOR_DESKTOP 0x000000FF
#define COLOR_DIMGRAY 0x696969FF
#define COLOR_DODGERBLUE 0x1E90FFFF
#define COLOR_FIREBRICK 0xB22222FF
#define COLOR_FLORALWHITE 0xFFFAF0FF
#define COLOR_FORESTGREEN 0x228B22FF
#define COLOR_FUCHSIA 0xFF00FFFF
#define COLOR_GAINSBORO 0xDCDCDCFF
#define COLOR_GHOSTWHITE 0xF8F8FFFF
#define COLOR_GOLDENROD 0xDAA520FF
#define COLOR_GRADIENTACTIVECAPTION 0xB9D1EAFF
#define COLOR_GRADIENTINACTIVECAPTION 0xD7E4F2FF
#define COLOR_GRAY 0x808080FF
#define COLOR_GRAYTEXT 0x808080FF
#define COLOR_GREENYELLOW 0xADFF2FFF
#define COLOR_HIGHLIGHT 0x3399FFFF
#define COLOR_HIGHLIGHTTEXT 0xFFFFFFFF
#define COLOR_HONEYDEW 0xF0FFF0FF
#define COLOR_HOTTRACK 0x0066CCFF
#define COLOR_INACTIVEBORDER 0xF4F7FCFF
#define COLOR_INACTIVECAPTION 0xBFCDDBFF
#define COLOR_INACTIVECAPTIONTEXT 0x434E54FF
#define COLOR_INDIANRED 0xCD5C5CFF
#define COLOR_INDIGO 0x4B0082FF
#define COLOR_INFO 0xFFFFE1FF
#define COLOR_INFOTEXT 0x000000FF
#define COLOR_IVORY 0xFFFFF0FF
#define COLOR_KHAKI 0xF0E68CFF
#define COLOR_LAVENDER 0xE6E6FAFF
#define COLOR_LAVENDERBLUSH 0xFFF0F5FF
#define COLOR_LAWNGREEN 0x7CFC00FF
#define COLOR_LEMONCHIFFON 0xFFFACDFF
#define COLOR_LIGHTCORAL 0xF08080FF
#define COLOR_LIGHTCYAN 0xE0FFFFFF
#define COLOR_LIGHTGOLDENRODYELLOW 0xFAFAD2FF
#define COLOR_LIGHTGRAY 0xD3D3D3FF
#define COLOR_LIGHTPINK 0xFFB6C1FF
#define COLOR_LIGHTSALMON 0xFFA07AFF
#define COLOR_LIGHTSEAGREEN 0x20B2AAFF
#define COLOR_LIGHTSKYBLUE 0x87CEFAFF
#define COLOR_LIGHTSLATEGRAY 0x778899FF
#define COLOR_LIGHTSTEELBLUE 0xB0C4DEFF
#define COLOR_LIGHTYELLOW 0xFFFFE0FF
#define COLOR_LIME 0x00FF00FF
#define COLOR_LIMEGREEN 0x32CD32FF
#define COLOR_LINEN 0xFAF0E6FF
#define COLOR_MAGENTA 0xFF00FFFF
#define COLOR_MAROON 0x800000FF
#define COLOR_MEDIUMAQUAMARINE 0x66CDAAFF
#define COLOR_MEDIUMBLUE 0x0000CDFF
#define COLOR_MEDIUMORCHID 0xBA55D3FF
#define COLOR_MEDIUMPURPLE 0x9370DBFF
#define COLOR_MEDIUMSEAGREEN 0x3CB371FF
#define COLOR_MEDIUMSLATEBLUE 0x7B68EEFF
#define COLOR_MEDIUMSPRINGGREEN 0x00FA9AFF
#define COLOR_MEDIUMTURQUOISE 0x48D1CCFF
#define COLOR_MEDIUMVIOLETRED 0xC71585FF
#define COLOR_MENU 0xF0F0F0FF
#define COLOR_MENUBAR 0xF0F0F0FF
#define COLOR_MENUHIGHLIGHT 0x3399FFFF
#define COLOR_MENUTEXT 0x000000FF
#define COLOR_MIDNIGHTBLUE 0x191970FF
#define COLOR_MINTCREAM 0xF5FFFAFF
#define COLOR_MISTYROSE 0xFFE4E1FF
#define COLOR_MOCCASIN 0xFFE4B5FF
#define COLOR_NAVAJOWHITE 0xFFDEADFF
#define COLOR_NAVY 0x000080FF
#define COLOR_OLDLACE 0xFDF5E6FF
#define COLOR_OLIVE 0x808000FF
#define COLOR_OLIVEDRAB 0x6B8E23FF
#define COLOR_ORANGERED 0xFF4500FF
#define COLOR_ORCHID 0xDA70D6FF
#define COLOR_PALEGOLDENROD 0xEEE8AAFF
#define COLOR_PALEGREEN 0x98FB98FF
#define COLOR_PALETURQUOISE 0xAFEEEEFF
#define COLOR_PALEVIOLETRED 0xDB7093FF
#define COLOR_PAPAYAWHIP 0xFFEFD5FF
#define COLOR_PEACHPUFF 0xFFDAB9FF
#define COLOR_PERU 0xCD853FFF
#define COLOR_PINK 0xFFC0CBFF
#define COLOR_PLUM 0xDDA0DDFF
#define COLOR_POWDERBLUE 0xB0E0E6FF
#define COLOR_ROSYBROWN 0xBC8F8FFF
#define COLOR_ROYALBLUE 0x4169E1FF
#define COLOR_SADDLEBROWN 0x8B4513FF
#define COLOR_SALMON 0xFA8072FF
#define COLOR_SANDYBROWN 0xF4A460FF
#define COLOR_SCROLLBAR 0xC8C8C8FF
#define COLOR_SEAGREEN 0x2E8B57FF
#define COLOR_SEASHELL 0xFFF5EEFF
#define COLOR_SIENNA 0xA0522DFF
#define COLOR_SILVER 0xC0C0C0FF
#define COLOR_SKYBLUE 0x87CEEBFF
#define COLOR_SLATEBLUE 0x6A5ACDFF
#define COLOR_SLATEGRAY 0x708090FF
#define COLOR_SNOW 0xFFFAFAFF
#define COLOR_SPRINGGREEN 0x00FF7FFF
#define COLOR_STEELBLUE 0x4682B4FF
#define COLOR_TAN 0xD2B48CFF
#define COLOR_TEAL 0x008080FF
#define COLOR_THISTLE 0xD8BFD8FF
#define COLOR_TOMATO 0xFF6347FF
#define COLOR_TRANSPARENT 0xFFFFFF00
#define COLOR_TURQUOISE 0x40E0D0FF
#define COLOR_VIOLET 0xEE82EEFF
#define COLOR_WHEAT 0xF5DEB3FF
#define COLOR_WHITESMOKE 0xF5F5F5FF
#define COLOR_WINDOW 0xFFFFFFFF
#define COLOR_WINDOWFRAME 0x646464FF
#define COLOR_WINDOWTEXT 0x000000FF
#define COLOR_YELLOWGREEN 0x9ACD32FF
#define STEALTH_ORANGE 0xFF880000
#define STEALTH_OLIVE 0x66660000
#define STEALTH_GREEN 0x33DD1100
#define STEALTH_PINK 0xFF22EE00
#define STEALTH_BLUE 0x0077BB00

#define COLOR_RADIO2					(0xAEA490FF)

#define COLOUR_WHITE						0xFFFFFFFF
#define EMBED_WHITE							"{FFFFFF}"
#define COLOUR_BLACK 						0x000000FF
#define EMBED_BLACK 						"{000000}"
#define COLOUR_TOMATO						0xFF6347FF
#define COLOR_BREEZEADMIN               (0x62869dFF)
#define EMBED_TOMATO						"{FF6347}"
#define COLOUR_GOLD							0xFFD700FF
#define EMBED_GOLD							"{FFD700}"
#define COLOUR_EASTSIDE		   	 			0xBEA1D3FF
#define EMBED_EASTSIDE						"{BEA1D3}"
#define COLOUR_LAVENDERPURPLE    	 		0x9374ABFF
#define EMBED_LAVENDERPURPLE    		    "{9374AB}"
#define COLOUR_PASTELGREEN					0x90EE90FF
#define EMBED_PASTELGREEN					"{90EE90}"
#define COLOUR_PEPPERMINT					0xD1EED1FF
#define EMBED_PEPPERMINT					"{D1EED1}"
#define COLOUR_ALTO							0xD6D6D6FF // aka: COLOUR_GRAY
#define EMBED_ALTO 							"{D6D6D6}" // aka: COLOUR_GRAY
#define COLOUR_TURBO            			0xF0F000FF
#define EMBED_TURBO	            			"{F0F000}"
#define COLOUR_TULIPTREE	        		0xE5C43EFF
#define EMBED_TULIPTREE	        			"{E5C43E}"
#define COLOUR_BRIGHTRED 					0xAA0000FF
#define EMBED_BRIGHTRED 					"{AA0000}"
#define COLOUR_MERCURY 						0xE5E5E5FF // aka: COLOUR_FADE_1
#define EMBED_MERCURY 						"{E5E5E5}" // aka: EMBED_FADE_1
#define COLOUR_SILVER 						0xCCCCCCFF // aka: COLOUR_FADE_2
#define EMBED_SILVER 						"{CCCCCC}" // aka: EMBED_FADE_2
#define COLOUR_NOBEL 						0xB3B3B3FF // aka: COLOUR_FADE_3
#define EMBED_NOBEL 						"{B3B3B3}" // aka: COLOUR_FADE_3
#define COLOUR_DUSTYGRAY 					0x999999FF // aka: COLOUR_FADE_4
#define COLOUR_CITRINEWHITE 				0xF9F4CDFF
#define COLOUR_DANDELION 					0xFED85DFF
#define EMBED_DANDELION 					"{FED85D}"
#define COLOUR_ORCHID 						0xDD66DDFF
#define EMBED_ORCHID	 					"{DD66DD}"
#define COLOUR_MALIBU 						0x8D8DFFFF
#define COLOUR_APPLE 						0x33AA33FF
#define COLOUR_BROOM 						0xFFFF15FF
#define EMBED_BROOM 						"{FFFF15}"
#define COLOUR_POLOBLUE 					0x8993CBFF
#define EMBED_POLOBLUE  					"{8993CB}"
#define COLOUR_COPBLUE 						0x3333FFFF
#define COLOUR_PRIMROSE 					0xF0F2A5FF
#define EMBED_ORANGE						"{fea75d}"
#define COLOUR_ORANGE						0xfea75dFF
#define COLOUR_TURQUOISE					0x9FA8C7FF
#define EMBED_TURQUOISE						"{9FA8C7}"
#define COLOUR_CURIOUSBLUE	                0x3697DAFF
#define EMBED_CURIOUSBLUE	                "{3697DA}"
#define COLOUR_SPINDLE		                0xB9D6EAFF
#define EMBED_SPINDLE		                "{B9D6EA}"
#define COLOUR_BLIZZARDBLUE                 0xA7D1EEFF
#define EMBED_BLIZZARDBLUE                  "{A7D1EE}"
#define COLOUR_SEAPINK                      0xEE9090FF
#define EMBED_SEAPINK                       "{EE9090}"
#define COLOUR_SOFTPEACH                    0xEEE3E3FF
#define EMBED_SOFTPEACH                     "{EEE3E3}"
#define COLOUR_CHALKY                       0xEEC490FF
#define EMBED_CHALKY                        "{EEC490}"
#define COLOUR_WHITEROCK                    0xEEE6DBFF
#define EMBED_WHITEROCK                     "{EEE6DB}"
#define COLOUR_SUNGLOW                      0xFCC728FF
#define EMBED_SUNGLOW                       "{FCC728}"
#define COLOUR_VISTABLUE                    0x81CBADFF
#define EMBED_VISTABLUE                     "{81CBAD}"
#define COLOUR_SILVERTREE                   0x4FB089FF
#define EMBED_SILVERTREE                    "{4FB089}"
#define COLOUR_LAPALMA                      0x3A841BFF
#define EMBED_LAPALMA                       "{3A841B}"
#define COLOUR_AMARANTH                     0xEC4652FF
#define EMBED_AMARANTH                      "{EC4652}"
#define COLOUR_ATLANTIS                     0x97CD2DFF
#define COLOUR_RHABDOMYOLISIS               0x32A832FF
#define COLOUR_YELLOW	                    0xFFFF00FF

// Color data
enum ColourData
{
    coID,
    coName[32],
    coHexValue,
    coEmbedValue[9],
    coTextureModelID,
    coTxdName[32],
    coTextureName[32],
    coVehicleColorID,
    coARGB
}

new Colours[][ColourData] = 
{
    {0, "Yok", 0x000000FF, "{000000}", -1, "none", "none", 0, 0},
    {1, "Wild Sand", 0xF5F5F5FF, "{F5F5F5}", -1, "none", "none", 1, 0xFFF5F5F5},
    {2, "Jelly Bean", 0x2A77A1FF, "{2A77A1}", -1, "none", "none", 2, 0xFF2A77A1},
    {3, "Red Devil", 0x840410FF, "{840410}", -1, "none", "none", 3, 0xFF840410},
    {4, "Outer Space", 0x263739FF, "{263739}", -1, "none", "none", 4, 0xFF263739},
    {5, "Cannon Pink", 0x86446EFF, "{86446E}", -1, "none", "none", 5, 0xFF86446E},
    {6, "Golden Bell", 0xD78E10FF, "{D78E10}", -1, "none", "none", 6, 0xFFD78E10},
    {7, "Steel Blue", 0x4C75B7FF, "{4C75B7}", -1, "none", "none", 7, 0xFF4C75B7},
    {8, "French Gray", 0xBDBEC6FF, "{BDBEC6}", -1, "none", "none", 8, 0xFFBDBEC6},
    {9, "Nevada", 0x5E7072FF, "{5E7072}", -1, "none", "none", 9, 0xFF5E7072},
    {10, "Blue Bayoux", 0x46597AFF, "{46597A}", -1, "none", "none", 10, 0xFF46597A},
    {11, "Shuttle Gray", 0x656A79FF, "{656A79}", -1, "none", "none", 11, 0xFF656A79},
    {12, "Lynch", 0x5D7E8DFF, "{5D7E8D}", -1, "none", "none", 12, 0xFF5D7E8D},
    {13, "Abbey", 0x58595AFF, "{58595A}", -1, "none", "none", 13, 0xFF58595A},
    {14, "Tasman", 0xD6DAD6FF, "{D6DAD6}", -1, "none", "none", 14, 0xFFD6DAD6},
    {15, "Gray Chateau", 0x9CA1A3FF, "{9CA1A3}", -1, "none", "none", 15, 0xFF9CA1A3},
    {16, "Killarney", 0x335F3FFF, "{335F3F}", -1, "none", "none", 16, 0xFF335F3F},
    {17, "Dark Tan", 0x730E1AFF, "{730E1A}", -1, "none", "none", 17, 0xFF730E1A},
    {18, "Monarch", 0x7B0A2AFF, "{7B0A2A}", -1, "none", "none", 18, 0xFF7B0A2A},
    {19, "Dawn", 0x9F9D94FF, "{9F9D94}", -1, "none", "none", 19, 0xFF9F9D94},
    {20, "East Bay", 0x3B4E78FF, "{3B4E78}", -1, "none", "none", 20, 0xFF3B4E78},
    {21, "Tawny Port", 0x732E3EFF, "{732E3E}", -1, "none", "none", 21, 0xFF732E3E},
    {22, "Wine Berry", 0x691E3BFF, "{691E3B}", -1, "none", "none", 22, 0xFF691E3B},
    {23, "Natural Gray", 0x96918CFF, "{96918C}", -1, "none", "none", 23, 0xFF96918C},
    {24, "Abbey 2", 0x515459FF, "{515459}", -1, "none", "none", 24, 0xFF515459},
    {25, "Ship Gray", 0x3F3E45FF, "{3F3E45}", -1, "none", "none", 25, 0xFF3F3E45},
    {26, "Edward", 0xA5A9A7FF, "{A5A9A7}", -1, "none", "none", 26, 0xFFA5A9A7},
    {27, "Dorado", 0x635C5AFF, "{635C5A}", -1, "none", "none", 27, 0xFF635C5A},
    {28, "Fiord", 0x3D4A68FF, "{3D4A68}", -1, "none", "none", 28, 0xFF3D4A68},
    {29, "Dawn 2", 0x979592FF, "{979592}", -1, "none", "none", 29, 0xFF979592},
    {30, "Crater Brown", 0x421F21FF, "{421F21}", -1, "none", "none", 30, 0xFF421F21},
    {31, "Buccaneer", 0x5F272BFF, "{5F272B}", -1, "none", "none", 31, 0xFF5F272B},
    {32, "Bali Hai", 0x8494ABFF, "{8494AB}", -1, "none", "none", 32, 0xFF8494AB},
    {33, "Sirocco", 0x767B7CFF, "{767B7C}", -1, "none", "none", 33, 0xFF767B7C},
    {34, "Dove Gray", 0x646464FF, "{646464}", -1, "none", "none", 34, 0xFF646464},
    {35, "Chicago", 0x5A5752FF, "{5A5752}", -1, "none", "none", 35, 0xFF5A5752},
    {36, "Shark", 0x252527FF, "{252527}", -1, "none", "none", 36, 0xFF252527},
    {37, "Outer Space 2", 0x2D3A35FF, "{2D3A35}", -1, "none", "none", 37, 0xFF2D3A35},
    {38, "Mantle", 0x93A396FF, "{93A396}", -1, "none", "none", 38, 0xFF93A396},
    {39, "Pale Sky", 0x6D7A88FF, "{6D7A88}", -1, "none", "none", 39, 0xFF6D7A88},
    {40, "Cocoa Brown", 0x221918FF, "{221918}", -1, "none", "none", 40, 0xFF221918},
    {41, "Flint", 0x6F675FFF, "{6F675F}", -1, "none", "none", 41, 0xFF6F675F},
    {42, "Merlot", 0x7C1C2AFF, "{7C1C2A}", -1, "none", "none", 42, 0xFF7C1C2A},
    {43, "Cab Sav", 0x5F0A15FF, "{5F0A15}", -1, "none", "none", 43, 0xFF5F0A15},
    {44, "Celtic", 0x193826FF, "{193826}", -1, "none", "none", 44, 0xFF193826},
    {45, "Espresso", 0x5D1B20FF, "{5D1B20}", -1, "none", "none", 45, 0xFF5D1B20},
    {46, "Gurkha", 0x9D9872FF, "{9D9872}", -1, "none", "none", 46, 0xFF9D9872},
    {47, "Pablo", 0x7A7560FF, "{7A7560}", -1, "none", "none", 47, 0xFF7A7560},
    {48, "Lemon Grass", 0x989586FF, "{989586}", -1, "none", "none", 48, 0xFF989586},
    {49, "Edward 2", 0xADB0B0FF, "{ADB0B0}", -1, "none", "none", 49, 0xFFADB0B0},
    {50, "Gunsmoke", 0x848988FF, "{848988}", -1, "none", "none", 50, 0xFF848988},
    {51, "Stromboli", 0x304F45FF, "{304F45}", -1, "none", "none", 51, 0xFF304F45},
    {52, "Cutty Sark", 0x4D6268FF, "{4D6268}", -1, "none", "none", 52, 0xFF4D6268},
    {53, "Bunting", 0x162248FF, "{162248}", -1, "none", "none", 53, 0xFF162248},
    {54, "Pickled Bluewood", 0x272F4BFF, "{272F4B}", -1, "none", "none", 54, 0xFF272F4B},
    {55, "Roman Coffee", 0x7D6256FF, "{7D6256}", -1, "none", "none", 55, 0xFF7D6256},
    {56, "Gray Chateau 2", 0x9EA4ABFF, "{9EA4AB}", -1, "none", "none", 56, 0xFF9EA4AB},
    {57, "Pale Oyster", 0x9C8D71FF, "{9C8D71}", -1, "none", "none", 57, 0xFF9C8D71},
    {58, "Persian Plum", 0x6D1822FF, "{6D1822}", -1, "none", "none", 58, 0xFF6D1822},
    {59, "Blue Bayoux 2", 0x4E6881FF, "{4E6881}", -1, "none", "none", 59, 0xFF4E6881},
    {60, "Star Dust", 0x9C9C98FF, "{9C9C98}", -1, "none", "none", 60, 0xFF9C9C98},
    {61, "Cape Palliser", 0x917347FF, "{917347}", -1, "none", "none", 61, 0xFF917347},
    {62, "Persian Plum 2", 0x661C26FF, "{661C26}", -1, "none", "none", 62, 0xFF661C26},
    {63, "Oslo Gray", 0x949D9FFF, "{949D9F}", -1, "none", "none", 63, 0xFF949D9F},
    {64, "Edward 3", 0xA4A7A5FF, "{A4A7A5}", -1, "none", "none", 64, 0xFFA4A7A5},
    {65, "Sycamore", 0x8E8C46FF, "{8E8C46}", -1, "none", "none", 65, 0xFF8E8C46},
    {66, "Jon", 0x341A1EFF, "{341A1E}", -1, "none", "none", 66, 0xFF341A1E},
    {67, "Slate Gray", 0x6A7A8CFF, "{6A7A8C}", -1, "none", "none", 67, 0xFF6A7A8C},
    {68, "Locust", 0xAAAD8EFF, "{AAAD8E}", -1, "none", "none", 68, 0xFFAAAD8E},
    {69, "Del Rio", 0xAB988FFF, "{AB988F}", -1, "none", "none", 69, 0xFFAB988F},
    {70, "Old Brick", 0x851F2EFF, "{851F2E}", -1, "none", "none", 70, 0xFF851F2E},
    {71, "Lynch 2", 0x6F8297FF, "{6F8297}", -1, "none", "none", 71, 0xFF6F8297},
    {72, "Fuscous Gray", 0x585853FF, "{585853}", -1, "none", "none", 72, 0xFF585853},
    {73, "Sage", 0x9AA790FF, "{9AA790}", -1, "none", "none", 73, 0xFF9AA790},
    {74, "Persian Plum 3", 0x601A23FF, "{601A23}", -1, "none", "none", 74, 0xFF601A23},
    {75, "Charade", 0x20202CFF, "{20202C}", -1, "none", "none", 75, 0xFF20202C},
    {76, "Dawn 3", 0xA4A096FF, "{A4A096}", -1, "none", "none", 76, 0xFFA4A096},
    {77, "Hillary", 0xAA9D84FF, "{AA9D84}", -1, "none", "none", 77, 0xFFAA9D84},
    {78, "Crown of Thorns", 0x78222BFF, "{78222B}", -1, "none", "none", 78, 0xFF78222B},
    {79, "Madison", 0x0E316DFF, "{0E316D}", -1, "none", "none", 79, 0xFF0E316D},
    {80, "Pablo 2", 0x722A3FFF, "{722A3F}", -1, "none", "none", 80, 0xFF722A3F},
    {81, "Pablo 3", 0x7B715EFF, "{7B715E}", -1, "none", "none", 81, 0xFF7B715E},
    {82, "Crown of Thorns 2", 0x741D28FF, "{741D28}", -1, "none", "none", 82, 0xFF741D28},
    {83, "Ebony Clay", 0x1E2E32FF, "{1E2E32}", -1, "none", "none", 83, 0xFF1E2E32},
    {84, "Rock", 0x4D322FFF, "{4D322F}", -1, "none", "none", 84, 0xFF4D322F},
    {85, "Claret", 0x7C1B44FF, "{7C1B44}", -1, "none", "none", 85, 0xFF7C1B44},
    {86, "Parsley", 0x2E5B20FF, "{2E5B20}", -1, "none", "none", 86, 0xFF2E5B20},
    {87, "Chambray", 0x395A83FF, "{395A83}", -1, "none", "none", 87, 0xFF395A83},
    {88, "Tawny Port 2", 0x6D2837FF, "{6D2837}", -1, "none", "none", 88, 0xFF6D2837},
    {89, "Gray Olive", 0xA7A28FFF, "{A7A28F}", -1, "none", "none", 89, 0xFFA7A28F},
    {90, "Edward 4", 0xAFB1B1FF, "{AFB1B1}", -1, "none", "none", 90, 0xFFAFB1B1},
    {91, "Oxford Blue", 0x364155FF, "{364155}", -1, "none", "none", 91, 0xFF364155},
    {92, "Salt Box", 0x6D6C6EFF, "{6D6C6E}", -1, "none", "none", 92, 0xFF6D6C6E},
    {93, "Surfie Green", 0x0F6A89FF, "{0F6A89}", -1, "none", "none", 93, 0xFF0F6A89},
    {94, "Cello", 0x204B6BFF, "{204B6B}", -1, "none", "none", 94, 0xFF204B6B},
    {95, "Rhino", 0x2B3E57FF, "{2B3E57}", -1, "none", "none", 95, 0xFF2B3E57},
    {96, "Pewter", 0x9B9F9DFF, "{9B9F9D}", -1, "none", "none", 96, 0xFF9B9F9D},
    {97, "Slate Gray 2", 0x6C8495FF, "{6C8495}", -1, "none", "none", 97, 0xFF6C8495},
    {98, "Wedgewood", 0x4D8495FF, "{4D8495}", -1, "none", "none", 98, 0xFF4D8495},
    {99, "Sandrift", 0xAE9B7FFF, "{AE9B7F}", -1, "none", "none", 99, 0xFFAE9B7F},
    {100, "Ming", 0x406C8FFF, "{406C8F}", -1, "none", "none", 100, 0xFF406C8F},
    {101, "Mirage", 0x1F253BFF, "{1F253B}", -1, "none", "none", 101, 0xFF1F253B},
    {102, "Sandrift 2", 0xAB9276FF, "{AB9276}", -1, "none", "none", 102, 0xFFAB9276},
    {103, "Chathams Blue", 0x134573FF, "{134573}", -1, "none", "none", 103, 0xFF134573},
    {104, "Arrowtown", 0x96816CFF, "{96816C}", -1, "none", "none", 104, 0xFF96816C},
    {105, "Nevada 2", 0x64686AFF, "{64686A}", -1, "none", "none", 105, 0xFF64686A},
    {106, "Chathams Blue 2", 0x105082FF, "{105082}", -1, "none", "none", 106, 0xFF105082},
    {107, "Tallow", 0xA19983FF, "{A19983}", -1, "none", "none", 107, 0xFFA19983},
    {108, "Chambray 2", 0x385694FF, "{385694}", -1, "none", "none", 108, 0xFF385694},
    {109, "Trout", 0x525661FF, "{525661}", -1, "none", "none", 109, 0xFF525661},
    {110, "Shadow", 0x7F6956FF, "{7F6956}", -1, "none", "none", 110, 0xFF7F6956},
    {111, "Oslo Gray 2", 0x8C929AFF, "{8C929A}", -1, "none", "none", 111, 0xFF8C929A},
    {112, "Blue Bayoux 3", 0x596E87FF, "{596E87}", -1, "none", "none", 112, 0xFF596E87},
    {113, "Woody Brown", 0x473532FF, "{473532}", -1, "none", "none", 113, 0xFF473532},
    {114, "Mineral Green", 0x44624FFF, "{44624F}", -1, "none", "none", 114, 0xFF44624F},
    {115, "Monarch", 0x730A27FF, "{730A27}", -1, "none", "none", 115, 0xFF730A27},
    {116, "Cloud Burst", 0x223457FF, "{223457}", -1, "none", "none", 116, 0xFF223457},
    {117, "Dark Tan", 0x640D1BFF, "{640D1B}", -1, "none", "none", 117, 0xFF640D1B},
    {118, "Cadet Blue", 0xA3ADC6FF, "{A3ADC6}", -1, "none", "none", 118, 0xFFA3ADC6},
    {119, "Dorado 2", 0x695853FF, "{695853}", -1, "none", "none", 119, 0xFF695853},
    {120, "Pale Oyster 2", 0x9B8B80FF, "{9B8B80}", -1, "none", "none", 120, 0xFF9B8B80},
    {121, "Maroon Oak", 0x620B1CFF, "{620B1C}", -1, "none", "none", 121, 0xFF620B1C},
    {122, "Abbey 3", 0x5B5D5EFF, "{5B5D5E}", -1, "none", "none", 122, 0xFF5B5D5E},
    {123, "Irish Coffee", 0x624428FF, "{624428}", -1, "none", "none", 123, 0xFF624428},
    {124, "Merlot 2", 0x731827FF, "{731827}", -1, "none", "none", 124, 0xFF731827},
    {125, "Biscay", 0x1B376DFF, "{1B376D}", -1, "none", "none", 125, 0xFF1B376D},
    {126, "Deep Blush", 0xEC6AAEFF, "{EC6AAE}", -1, "none", "none", 126, 0xFFEC6AAE},
    {127, "Black", 0x000000FF, "{000000}", -1, "none", "none", 127, 0xFF000000},
    {128, "Bilbao", 0x177517FF, "{177517}", -1, "none", "none", 128, 0xFF177517},
    {129, "Graphite", 0x210606FF, "{210606}", -1, "none", "none", 129, 0xFF210606},
    {130, "Chathams Blue", 0x125478FF, "{125478}", -1, "none", "none", 130, 0xFF125478},
    {131, "Clinker", 0x452A0DFF, "{452A0D}", -1, "none", "none", 131, 0xFF452A0D},
    {132, "Cocoa Bean", 0x571E1EFF, "{571E1E}", -1, "none", "none", 132, 0xFF571E1E},
    {133, "Black Forest", 0x010701FF, "{010701}", -1, "none", "none", 133, 0xFF010701},
    {134, "Port Gore", 0x25225AFF, "{25225A}", -1, "none", "none", 134, 0xFF25225A},
    {135, "Jelly Bean 2", 0x2C89AAFF, "{2C89AA}", -1, "none", "none", 135, 0xFF2C89AA},
    {136, "Fuchsia Blue", 0x8A4DBDFF, "{8A4DBD}", -1, "none", "none", 136, 0xFF8A4DBD},
    {137, "Apple", 0x35963AFF, "{35963A}", -1, "none", "none", 137, 0xFF35963A},
    {138, "Nobel", 0xB7B7B7FF, "{B7B7B7}", -1, "none", "none", 138, 0xFFB7B7B7},
    {139, "East Bay 2", 0x464C8DFF, "{464C8D}", -1, "none", "none", 139, 0xFF464C8D},
    {140, "Oslo Gray 3", 0x84888CFF, "{84888C}", -1, "none", "none", 140, 0xFF84888C},
    {141, "Makara", 0x817867FF, "{817867}", -1, "none", "none", 141, 0xFF817867},
    {142, "Crete", 0x817A26FF, "{817A26}", -1, "none", "none", 142, 0xFF817A26},
    {143, "Salt Box 2", 0x6A506FFF, "{6A506F}", -1, "none", "none", 143, 0xFF6A506F},
    {144, "Mulled Wine", 0x583E6FFF, "{583E6F}", -1, "none", "none", 144, 0xFF583E6F},
    {145, "Olivine", 0x8CB972FF, "{8CB972}", -1, "none", "none", 145, 0xFF8CB972},
    {146, "Strikemaster", 0x824F78FF, "{824F78}", -1, "none", "none", 146, 0xFF824F78},
    {147, "Plum", 0x6D276AFF, "{6D276A}", -1, "none", "none", 147, 0xFF6D276A},
    {148, "Rangoon Green", 0x1E1D13FF, "{1E1D13}", -1, "none", "none", 148, 0xFF1E1D13},
    {149, "Graphite 2", 0x1E1306FF, "{1E1306}", -1, "none", "none", 149, 0xFF1E1306},
    {150, "Log Cabin", 0x1F2518FF, "{1F2518}", -1, "none", "none", 150, 0xFF1F2518},
    {151, "Tom Thumb", 0x2C4531FF, "{2C4531}", -1, "none", "none", 151, 0xFF2C4531},
    {152, "Matisse", 0x1E4C99FF, "{1E4C99}", -1, "none", "none", 152, 0xFF1E4C99},
    {153, "Stromboli 2", 0x2E5F43FF, "{2E5F43}", -1, "none", "none", 153, 0xFF2E5F43},
    {154, "Eucalyptus", 0x1E9948FF, "{1E9948}", -1, "none", "none", 154, 0xFF1E9948},
    {155, "Eastern Blue", 0x1E9999FF, "{1E9999}", -1, "none", "none", 155, 0xFF1E9999},
    {156, "Gurkha", 0x999976FF, "{999976}", -1, "none", "none", 156, 0xFF999976},
    {157, "Waterloo", 0x7C8499FF, "{7C8499}", -1, "none", "none", 157, 0xFF7C8499},
    {158, "Prairie Sand", 0x992E1EFF, "{992E1E}", -1, "none", "none", 158, 0xFF992E1E},
    {159, "Graphite 3", 0x2C1E08FF, "{2C1E08}", -1, "none", "none", 159, 0xFF2C1E08},
    {160, "Deep Forest Green", 0x142407FF, "{142407}", -1, "none", "none", 160, 0xFF142407},
    {161, "Vin Rouge", 0x993E4DFF, "{993E4D}", -1, "none", "none", 161, 0xFF993E4D},
    {162, "Matisse 2", 0x1E4C99FF, "{1E4C99}", -1, "none", "none", 162, 0xFF1E4C99},
    {163, "Elm", 0x198181FF, "{198181}", -1, "none", "none", 163, 0xFF198181},
    {164, "Mirage 2", 0x1A292AFF, "{1A292A}", -1, "none", "none", 164, 0xFF1A292A},
    {165, "Blumine", 0x16616FFF, "{16616F}", -1, "none", "none", 165, 0xFF16616F},
    {166, "Blumine 2", 0x1B6687FF, "{1B6687}", -1, "none", "none", 166, 0xFF1B6687},
    {167, "Royal Purple", 0x6C3F99FF, "{6C3F99}", -1, "none", "none", 167, 0xFF6C3F99},
    {168, "Van Cleef", 0x481A0EFF, "{481A0E}", -1, "none", "none", 168, 0xFF481A0E},
    {169, "Kimberly", 0x7A7399FF, "{7A7399}", -1, "none", "none", 169, 0xFF7A7399},
    {170, "Kimberly 2", 0x746D99FF, "{746D99}", -1, "none", "none", 170, 0xFF746D99},
    {171, "Gigas", 0x53387EFF, "{53387E}", -1, "none", "none", 171, 0xFF53387E},
    {172, "Turtle Green", 0x222407FF, "{222407}", -1, "none", "none", 172, 0xFF222407},
    {173, "Clinker 2", 0x3E190CFF, "{3E190C}", -1, "none", "none", 173, 0xFF3E190C},
    {174, "Van Cleef 2", 0x46210EFF, "{46210E}", -1, "none", "none", 174, 0xFF46210E},
    {175, "Old Brick 2", 0x991E1EFF, "{991E1E}", -1, "none", "none", 175, 0xFF991E1E},
    {176, "Strikemaster 2", 0x8D4C8DFF, "{8D4C8D}", -1, "none", "none", 176, 0xFF8D4C8D},
    {177, "Strikemaster 3", 0x805B80FF, "{805B80}", -1, "none", "none", 177, 0xFF805B80},
    {178, "Affair", 0x7B3E7EFF, "{7B3E7E}", -1, "none", "none", 178, 0xFF7B3E7E},
    {179, "Wine Berry 2", 0x3C1737FF, "{3C1737}", -1, "none", "none", 179, 0xFF3C1737},
    {180, "Peanut", 0x733517FF, "{733517}", -1, "none", "none", 180, 0xFF733517},
    {181, "Falu Red", 0x781818FF, "{781818}", -1, "none", "none", 181, 0xFF781818},
    {182, "Mocha", 0x83341AFF, "{83341A}", -1, "none", "none", 182, 0xFF83341A},
    {183, "Prairie Sand 2", 0x8E2F1CFF, "{8E2F1C}", -1, "none", "none", 183, 0xFF8E2F1C},
    {184, "Cosmic", 0x7E3E53FF, "{7E3E53}", -1, "none", "none", 184, 0xFF7E3E53},
    {185, "Fedora", 0x7C6D7CFF, "{7C6D7C}", -1, "none", "none", 185, 0xFF7C6D7C},
    {186, "Black Forest 2", 0x020C02FF, "{020C02}", -1, "none", "none", 186, 0xFF020C02},
    {187, "Deep Forest Green 2", 0x072407FF, "{072407}", -1, "none", "none", 187, 0xFF072407},
    {188, "Seaweed", 0x163012FF, "{163012}", -1, "none", "none", 188, 0xFF163012},
    {189, "Celtic 2", 0x16301BFF, "{16301B}", -1, "none", "none", 189, 0xFF16301B},
    {190, "Finn", 0x642B4FFF, "{642B4F}", -1, "none", "none", 190, 0xFF642B4F},
    {191, "Goblin", 0x368452FF, "{368452}", -1, "none", "none", 191, 0xFF368452},
    {192, "Zorba", 0x999590FF, "{999590}", -1, "none", "none", 192, 0xFF999590},
    {193, "Regent Gray", 0x818D96FF, "{818D96}", -1, "none", "none", 193, 0xFF818D96},
    {194, "Citron", 0x99991EFF, "{99991E}", -1, "none", "none", 194, 0xFF99991E},
    {195, "Asparagus", 0x7F994CFF, "{7F994C}", -1, "none", "none", 195, 0xFF7F994C},
    {196, "Oslo Gray 4", 0x839292FF, "{839292}", -1, "none", "none", 196, 0xFF839292},
    {197, "Pacifika", 0x788222FF, "{788222}", -1, "none", "none", 197, 0xFF788222},
    {198, "Sapphire", 0x2B3C99FF, "{2B3C99}", -1, "none", "none", 198, 0xFF2B3C99},
    {199, "Waiouru", 0x3A3A0BFF, "{3A3A0B}", -1, "none", "none", 199, 0xFF3A3A0B},
    {200, "Shadow 2", 0x8A794EFF, "{8A794E}", -1, "none", "none", 200, 0xFF8A794E},
    {201, "Blue Zodiac", 0x0E1F49FF, "{0E1F49}", -1, "none", "none", 201, 0xFF0E1F49},
    {202, "Celtic 3", 0x15371CFF, "{15371C}", -1, "none", "none", 202, 0xFF15371C},
    {203, "Big Stone", 0x15273AFF, "{15273A}", -1, "none", "none", 203, 0xFF15273A},
    {204, "San Juan", 0x375775FF, "{375775}", -1, "none", "none", 204, 0xFF375775},
    {205, "Black Pearl", 0x060820FF, "{060820}", -1, "none", "none", 205, 0xFF060820},
    {206, "Black Pearl 2", 0x071326FF, "{071326}", -1, "none", "none", 206, 0xFF071326},
    {207, "Blue Dianne", 0x20394BFF, "{20394B}", -1, "none", "none", 207, 0xFF20394B},
    {208, "St. Tropaz", 0x2C5089FF, "{2C5089}", -1, "none", "none", 208, 0xFF2C5089},
    {209, "Chathams Blue", 0x15426CFF, "{15426C}", -1, "none", "none", 209, 0xFF15426C},
    {210, "Blue Zodiac 2", 0x103250FF, "{103250}", -1, "none", "none", 210, 0xFF103250},
    {211, "Lucky Point", 0x241663FF, "{241663}", -1, "none", "none", 211, 0xFF241663},
    {212, "Cherrywood", 0x692015FF, "{692015}", -1, "none", "none", 212, 0xFF692015},
    {213, "Manatee", 0x8C8D94FF, "{8C8D94}", -1, "none", "none", 213, 0xFF8C8D94},
    {214, "Saratoga", 0x516013FF, "{516013}", -1, "none", "none", 214, 0xFF516013},
    {215, "Pine Tree", 0x090F02FF, "{090F02}", -1, "none", "none", 215, 0xFF090F02},
    {216, "Potters Clay", 0x8C573AFF, "{8C573A}", -1, "none", "none", 216, 0xFF8C573A},
    {217, "Smalt Blue", 0x52888EFF, "{52888E}", -1, "none", "none", 217, 0xFF52888E},
    {218, "Au Chico", 0x995C52FF, "{995C52}", -1, "none", "none", 218, 0xFF995C52},
    {219, "Rope", 0x99581EFF, "{99581E}", -1, "none", "none", 219, 0xFF99581E},
    {220, "Vin Rouge 2", 0x993A63FF, "{993A63}", -1, "none", "none", 220, 0xFF993A63},
    {221, "Barley Corn", 0x998F4EFF, "{998F4E}", -1, "none", "none", 221, 0xFF998F4E},
    {222, "Prairie Sand 3", 0x99311EFF, "{99311E}", -1, "none", "none", 222, 0xFF99311E},
    {223, "Blue Zodiac 3", 0x0D1842FF, "{0D1842}", -1, "none", "none", 223, 0xFF0D1842},
    {224, "Cocoa Bean 2", 0x521E1EFF, "{521E1E}", -1, "none", "none", 224, 0xFF521E1E},
    {225, "Waiouru 2", 0x42420DFF, "{42420D}", -1, "none", "none", 225, 0xFF42420D},
    {226, "Vida Loca", 0x4C991EFF, "{4C991E}", -1, "none", "none", 226, 0xFF4C991E},
    {227, "Bottle Green", 0x082A1DFF, "{082A1D}", -1, "none", "none", 227, 0xFF082A1D},
    {228, "Hacienda", 0x96821DFF, "{96821D}", -1, "none", "none", 228, 0xFF96821D},
    {229, "Forest Green", 0x197F19FF, "{197F19}", -1, "none", "none", 229, 0xFF197F19},
    {230, "Cedar", 0x3B141FFF, "{3B141F}", -1, "none", "none", 230, 0xFF3B141F},
    {231, "Sepia", 0x745217FF, "{745217}", -1, "none", "none", 231, 0xFF745217},
    {232, "Vivid Violet", 0x893F8DFF, "{893F8D}", -1, "none", "none", 232, 0xFF893F8D},
    {233, "Disco", 0x7E1A6CFF, "{7E1A6C}", -1, "none", "none", 233, 0xFF7E1A6C},
    {234, "Deep Forest Green 3", 0x0B370BFF, "{0B370B}", -1, "none", "none", 234, 0xFF0B370B},
    {235, "Green House", 0x27450DFF, "{27450D}", -1, "none", "none", 235, 0xFF27450D},
    {236, "Bottle Green 2", 0x071F24FF, "{071F24}", -1, "none", "none", 236, 0xFF071F24},
    {237, "Cannon Pink", 0x784573FF, "{784573}", -1, "none", "none", 237, 0xFF784573},
    {238, "Potters Clay 2", 0x8A653AFF, "{8A653A}", -1, "none", "none", 238, 0xFF8A653A},
    {239, "Mocha 2", 0x732617FF, "{732617}", -1, "none", "none", 239, 0xFF732617},
    {240, "Lochinvar", 0x319490FF, "{319490}", -1, "none", "none", 240, 0xFF319490},
    {241, "Vida Loca 2", 0x56941DFF, "{56941D}", -1, "none", "none", 241, 0xFF56941D},
    {242, "Wine Berry 3", 0x59163DFF, "{59163D}", -1, "none", "none", 242, 0xFF59163D},
    {243, "Forest Green 2", 0x1B8A2FFF, "{1B8A2F}", -1, "none", "none", 243, 0xFF1B8A2F},
    {244, "Clinker 3", 0x38160BFF, "{38160B}", -1, "none", "none", 244, 0xFF38160B},
    {245, "Black Forest 3", 0x041804FF, "{041804}", -1, "none", "none", 245, 0xFF041804},
    {246, "Chambray 3", 0x355D8EFF, "{355D8E}", -1, "none", "none", 246, 0xFF355D8E},
    {247, "Rhino 2", 0x2E3F5BFF, "{2E3F5B}", -1, "none", "none", 247, 0xFF2E3F5B},
    {248, "Wine Berry 4", 0x561A28FF, "{561A28}", -1, "none", "none", 248, 0xFF561A28},
    {249, "Maroon Oak 2", 0x4E0E27FF, "{4E0E27}", -1, "none", "none", 249, 0xFF4E0E27},
    {250, "Flint 2", 0x706C67FF, "{706C67}", -1, "none", "none", 250, 0xFF706C67},
    {251, "Tuna", 0x3B3E42FF, "{3B3E42}", -1, "none", "none", 251, 0xFF3B3E42},
    {252, "Baltic Sea", 0x2E2D33FF, "{2E2D33}", -1, "none", "none", 252, 0xFF2E2D33},
    {253, "Gunsmoke 2", 0x7B7E7DFF, "{7B7E7D}", -1, "none", "none", 253, 0xFF7B7E7D},
    {254, "Masala", 0x4A4442FF, "{4A4442}", -1, "none", "none", 254, 0xFF4A4442},
    {255, "Pickled Bluewood 2", 0x28344EFF, "{28344E}", -1, "none", "none", 255, 0xFF28344E},
    {256, "Snow", 0x00000000, "{000000}", 3942, "bistro", "mp_snow"},
    {257, "Flagstone", 0x00000000, "{000000}", 3942, "bistro", "ahoodfence2", 0, 0x00000000},
    {258, "Grass", 0x00000000, "{000000}", 3908, "libertyfar", "Grass_128HV", 0, 0x00000000},
    {259, "Grass 2", 0x00000000, "{000000}", 3903, "libertyhi", "Grass", 0, 0x00000000},
    {260, "Clear water", 0x00000000, "{000000}", 3953, "rczero_track", "waterclear256", 0, 0x00000000},
    {261, "Grey rocks", 0x00000000, "{000000}", 3933, "weemap", "rocktb128", 0, 0x00000000},
    {262, "Dirty sand", 0x00000000, "{000000}", 4242, "seabed", "des_dirt1", 0, 0x00000000},
    {263, "Dirty sand 2", 0x00000000, "{000000}", 4242, "seabed", "sw_sand", 0, 0x00000000},
    {264, "Dunes on the desert (Sahara)", 0x00000000, "{000000}", 16008, "des_n", "des_ripplsand", 0, 0x00000000},
    {265, "Flagstone 2 (LS lighthouse)", 0x00000000, "{000000}", 13734, "hillcliff_lahills", "cobbles_kb_256", 0, 0x00000000},
    {266, "Red rocks (from desert)", 0x00000000, "{000000}", 16503, "desert", "des_redrock1", 0, 0x00000000},
    {267, "Wood floor 2 (brighter)", 0x00000000, "{000000}", 16407, "des_airfieldhus", "btdeck256", 0, 0x00000000},
    {268, "Yellow stripes (on the floor)", 0x00000000, "{000000}", 16102, "des_cen", "sm_conc_hatch", 0, 0x00000000},
    {269, "Roof with dark grey colour", 0x00000000, "{000000}", 16021, "des_geyser", "shingles1", 0, 0x00000000},
    {270, "Wall with rocks (looks nice)", 0x00000000, "{000000}", 16016, "des_n", "ranchwall1", 0, 0x00000000},
    {271, "Cracked ground", 0x00000000, "{000000}", 16571, "des_se1", "des_crackeddirt1", 0, 0x00000000},
    {272, "Grey rocks", 0x00000000, "{000000}", 18752, "Volcano", "rocktb128", 0, 0x00000000},
    {273, "Lava", 0x00000000, "{000000}", 18752, "Volcano", "lavalake", 0, 0x00000000},
    {274, "Ground under the lava", 0x00000000, "{000000}", 18752, "Volcano", "redgravel", 0, 0x00000000},
    {275, "Red rocks (from desert)", 0x00000000, "{000000}", 16503, "desert", "des_redrock1", 0, 0x00000000},
    {276, "Wood floor 2 (brighter)", 0x00000000, "{000000}", 16407, "des_airfieldhus", "btdeck256", 0, 0x00000000},
    {277, "Yellow stripes (on the floor)", 0x00000000, "{000000}", 16102, "des_cen", "sm_conc_hatch", 0, 0x00000000},
    {278, "Roof with dark grey colour", 0x00000000, "{000000}", 16021, "des_geyser", "shingles1", 0, 0x00000000},
    {279, "Wall with rocks (looks nice)", 0x00000000, "{000000}", 16016, "des_n", "ranchwall1", 0, 0x00000000},
    {280, "Cracked ground", 0x00000000, "{000000}", 16571, "des_se1", "des_crackeddirt1", 0, 0x00000000},
    {281, "Dance Floor", 0x00000000, "{000000}", 19128, "dancefloors", "dancefloor1", 0, 0x00000000},
    {282, "Camo Net", 0x00000000, "{000000}", 2068, "cj_ammo_net", "CJ_cammonet", 0, 0x00000000},
    {283, "White", 0x00000000, "{000000}", 18646, "matcolours", "white", 0, 0x00000000},
    {284, "Red", 0x00000000, "{000000}", 18646, "matcolours", "red", 0, 0x00000000},
    {285, "Blue", 0x00000000, "{000000}", 18646, "matcolours", "blue", 0, 0x00000000},
    {286, "Orange", 0x00000000, "{000000}", 18646, "matcolours", "orange", 0, 0x00000000},
    {287, "Green", 0x00000000, "{000000}", 18646, "matcolours", "green", 0, 0x00000000},
    {288, "Metal Plate", 0x00000000, "{000000}", 964, "cj_crate_will", "CJ_FLIGHT_CASE", 0, 0x00000000},
    {289, "Stop Sign", 0x00000000, "{000000}", 967, "cj_barr_set_1", "Stop2_64", 0, 0x00000000},
    {290, "Black and Yellow stripes", 0x00000000, "{000000}", 7981, "vgsairport02", "chevronYB_64", 0, 0x00000000},
    {291, "Red and White stripes", 0x00000000, "{000000}", 7981, "vgsairport02", "redwhite_stripe", 0, 0x00000000},
    {292, "Black and Yellow mesh", 0x00000000, "{000000}", 7980, "vegasairprtland", "gridchev_64HV", 0, 0x00000000},
    {293, "Yellow and White stripes", 0x00000000, "{000000}", 7980, "vegasairprtland", "chevron64HVa", 0, 0x00000000},
    {294, "Red Rectangles", 0x00000000, "{000000}", 6866, "vgncnstrct1", "Circus_gls_05", 0, 0x00000000},
    {295, "Red and White stripes", 0x00000000, "{000000}", 1281, "benches", "trafficcone", 0, 0x00000000},
    {296, "Large Mesh Glass", 0x00000000, "{000000}", 6295, "lawland2", "lightglass", 0, 0x00000000},
    {297, "Wood Planks", 0x00000000, "{000000}", 6295, "lawland2", "boardwalk2_la", 0, 0x00000000},
    {298, "Police Line", 0x00000000, "{000000}", 12938, "sw_apartments", "sw_policeline", 0, 0x00000000},
    {299, "Wigwam Motel - Wall", 0x00000000, "{000000}", 16004, "des_teepee", "des_wigwam", 0, 0x00000000},
    {300, "Wigwam Motel - Door", 0x00000000, "{000000}", 16004, "des_teepee", "des_wigwamdoor", 0, 0x00000000},
    {301, "Concrete with Dust", 0x00000000, "{000000}", 16004, "des_teepee", "des_dustconc", 0, 0x00000000},
    {302, "Grey Roof", 0x00000000, "{000000}", 16005, "des_stownmain2", "sanruf", 0, 0x00000000},
    {303, "Red Wooden Planks", 0x00000000, "{000000}", 16005, "des_stownmain2", "des_redslats", 0, 0x00000000},
    {304, "Light Purple Color", 0x00000000, "{000000}", 16005, "des_stownmain2", "duskyred_64", 0, 0x00000000},
    {305, "Old Wooden Planks", 0x00000000, "{000000}", 16005, "des_stownmain2", "des_ghotwood1", 0, 0x00000000},
    {306, "Wall 1 (Green)", 0x00000000, "{000000}", 16005, "des_stownmain2", "ws_green_wall1", 0, 0x00000000},
    {307, "Door 1 (Blue)", 0x00000000, "{000000}", 16005, "des_stownmain2", "alleydoor3", 0, 0x00000000},
    {308, "Wall 2 (Normal)", 0x00000000, "{000000}", 16005, "des_stownmain2", "newall4", 0, 0x00000000},
    {309, "Wall 3 (Normal)", 0x00000000, "{000000}", 16005, "des_stownmain2", "crencouwall1", 0, 0x00000000},
    {310, "Black Color", 0x00000000, "{000000}", 16005, "des_stownmain2", "black32", 0, 0x00000000},
    {311, "Cynder Blocks", 0x00000000, "{000000}", 5016, "ground3_las", "ws_bigstones", 0, 0x00000000},
    {312, "Jesus Saves", 0x00000000, "{000000}", 5016, "ground3_las", "mural01_LA", 0, 0x00000000},
    {313, "White Wall w/ windows", 0x00000000, "{000000}", 5033, "union_las", "lasunion98", 0, 0x00000000},
    {314, "Yello+Grey Diagonal Stripes", 0x00000000, "{000000}", 5033, "union_las", "ws_carparkwall2", 0, 0x00000000}
};


/*
 *          
 *      End Of Include
 *
 */
