#define MAX_CHARACTERS      (3)
#define AUTH_TIME           (300)
#define CHARACTER_UNACTIVE                     (0)
#define CHARACTER_ACTIVE                     (1)

#define GENDER_MALE                            (1)
#define GENDER_FEMALE                        (2)

#define RACE_WHITE                            (1)
#define RACE_BLACK                            (2)

#define MIN_CHARACTER_AGE                    (17)
#define MAX_CHARACTER_AGE                    (98)

#define CUSTOMIZATION_BACK                    (0)
#define CUSTOMIZATION_AGE                    (1)
#define CUSTOMIZATION_GENDER                (2)
#define CUSTOMIZATION_RACE                    (3)
#define CUSTOMIZATION_ORIGIN                (4)
#define CUSTOMIZATION_SKIN                    (5)
#define CUSTOMIZATION_VERIFY                (6)
#define CUSTOMIZATION_DONE                    (7)

#define DIALOG_EX                             EMBED_SILVER "örnek: " EMBED_WHITE

#define MYSQL_DEFAULT_HANDLE MySQL:1
#define MYSQL_INVALID_HANDLE MySQL:0
#define MYSQL_INVALID_CACHE Cache:0
#define MYSQL_INVALID_ORM ORM:0