new attach_city_model[] = {19904,19142,19515,18636,19161,19162,19521,19098,19200,19776,19777,18875,19942};
new bort_list_city[4] = {19834, 1238, 1228, 1459};

new attach_city_name[][] =
{
	"Turuncu Yelek",
	"Siyah Zýrh",
	"Gri Kurþun Geçirmez Yelek",
	"Polis Þapkasý 1",
	"Polis Þapkasý 2",
	"Polis Þapkasý 3",
	"Polis Þapkasý 4",
	"Polis Þapkasý",
	"Polis Motosiklet Kaský",
	"FBI Kart",
	"FBI Logo",
	"Çaðrý Cihazý",
	"Telsiz"
};

new bort_names_city[4][32] =
{
	"Bant",
	"Koni",
	"Bariyer",
	"Bariyer 2"
};